# Settings in this file are applied across all .qmd files
project: 
  type: website
  output-dir: docs
  
website: 
  title: "Nicholas LeDonne" 
  page-navigation: false
  # page-footer:
  #   right: ""
  sidebar:
    # background: "dark"
    logo: "images/profile-pic.jpg"
    pinned: true
    align: center
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/nicholas-ledonne-517114a7
        text: "LinkedIn"
      - icon: github
        href: https://github.com/NickLeDonne
        text: "GitHub"
      # - icon: cup-hot-fill
      #   href: https://buymeacoffee.com/nickledonne
      #   text: "Buy Me a Coffee"
      - icon: envelope-fill
        aria-label: email
        href: "mailto:NicholasLeDonne@gmail.com"
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Resume
      # - href: sheet.qmd
      #   text: Google Sheets
      # - href: pembrokes.qmd
      #   text: Pembroke's
      - section: projects/index.qmd
        text: Projects/Tools
        contents:
          - projects/pass-vba-through-r.qmd
          - projects/file-crawler.qmd
          - projects/vba-extractor.qmd
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 2

editor: visual